const express=require('express');const cors=require('cors');const Database=require('better-sqlite3');const bcrypt=require('bcryptjs');const jwt=require('jsonwebtoken');const multer=require('multer');const fs=require('fs');const path=require('path');
const app=express();const db=new Database('fonoplus.sqlite');const SECRET=process.env.JWT_SECRET||'change-me';fs.mkdirSync('uploads',{recursive:true});
app.use(cors());app.use(express.json({limit:'10mb'}));app.use('/uploads',express.static(path.join(__dirname,'uploads')));
db.exec(`CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,email TEXT UNIQUE,name TEXT,role TEXT,password_hash TEXT,active INTEGER DEFAULT 1,can_edit INTEGER DEFAULT 0,patient_id TEXT);
CREATE TABLE IF NOT EXISTS patients(id TEXT PRIMARY KEY,name TEXT,age INTEGER,profile TEXT,therapist_id TEXT,family_user_id TEXT,avatar TEXT);
CREATE TABLE IF NOT EXISTS plans(id TEXT PRIMARY KEY,patient_id TEXT,name TEXT,type TEXT,goal TEXT,active INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS activities(id TEXT PRIMARY KEY,plan_id TEXT,patient_id TEXT,type TEXT,metric TEXT,name TEXT,phoneme TEXT,position TEXT,level TEXT,stimulus TEXT,game TEXT,dose TEXT,active INTEGER DEFAULT 1);
CREATE TABLE IF NOT EXISTS records(id TEXT PRIMARY KEY,patient_id TEXT,plan_id TEXT,activity_id TEXT,context TEXT,metric TEXT,audio_url TEXT,duration REAL,noise_status TEXT,quality TEXT,note TEXT,created_at TEXT);
CREATE TABLE IF NOT EXISTS phoneme_samples(id TEXT PRIMARY KEY,patient_id TEXT,plan_id TEXT,activity_id TEXT,phoneme TEXT,position TEXT,level TEXT,stimulus TEXT,kind TEXT,audio_url TEXT,duration REAL,noise_status TEXT,quality TEXT,label TEXT DEFAULT 'pendiente',created_at TEXT,reviewed_by TEXT,reviewed_at TEXT,version TEXT);`);
function id(p){return p+'_'+Math.random().toString(36).slice(2,10)}function auth(req,res,next){const h=req.headers.authorization||'';try{req.user=jwt.verify(h.replace('Bearer ',''),SECRET);next()}catch(e){res.status(401).json({error:'unauthorized'})}}
function seed(){const row=db.prepare('SELECT COUNT(*) c FROM users').get();if(row.c)return;const pass=bcrypt.hashSync('admin123',10);db.prepare('INSERT INTO users(id,email,name,role,password_hash,active,can_edit) VALUES(?,?,?,?,?,?,?)').run('u1','admin@fonoplus.cl','Admin Fono+','admin',pass,1,1)}seed();
app.post('/api/login',(req,res)=>{const u=db.prepare('SELECT * FROM users WHERE email=? AND active=1').get(req.body.email);if(!u||!bcrypt.compareSync(req.body.password,u.password_hash))return res.status(401).json({error:'invalid'});const token=jwt.sign({id:u.id,role:u.role,email:u.email},SECRET,{expiresIn:'8h'});res.json({token,user:{id:u.id,email:u.email,name:u.name,role:u.role,canEdit:!!u.can_edit,patientId:u.patient_id}})});
app.get('/api/users',auth,(req,res)=>{if(req.user.role!=='admin')return res.status(403).json({error:'forbidden'});res.json(db.prepare('SELECT id,email,name,role,active,can_edit,patient_id FROM users').all())});
app.post('/api/users',auth,(req,res)=>{if(req.user.role!=='admin')return res.status(403).json({error:'forbidden'});const u=req.body;db.prepare('INSERT INTO users(id,email,name,role,password_hash,active,can_edit,patient_id) VALUES(?,?,?,?,?,?,?,?)').run(id('u'),u.email,u.name,u.role,bcrypt.hashSync(u.password||'demo123',10),1,u.canEdit?1:0,u.patientId||null);res.json({ok:true})});
app.get('/api/patients',auth,(req,res)=>res.json(db.prepare('SELECT * FROM patients').all()));
app.get('/api/dataset',auth,(req,res)=>{if(!['admin','therapist'].includes(req.user.role))return res.status(403).json({error:'forbidden'});res.json(db.prepare('SELECT * FROM phoneme_samples').all())});
const upload=multer({dest:'uploads/'});app.post('/api/phoneme-samples',auth,upload.single('audio'),(req,res)=>{const b=req.body, sampleId=id('ph'), audioUrl=req.file?'/uploads/'+req.file.filename:null;db.prepare(`INSERT INTO phoneme_samples(id,patient_id,plan_id,activity_id,phoneme,position,level,stimulus,kind,audio_url,duration,noise_status,quality,label,created_at,version) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(sampleId,b.patientId,b.planId,b.activityId,b.phoneme,b.position,b.level,b.stimulus,b.kind,audioUrl,Number(b.duration||0),b.noiseStatus,b.quality,b.label||'pendiente',new Date().toISOString(),b.version||'');res.json({id:sampleId,audioUrl})});
app.patch('/api/phoneme-samples/:id/label',auth,(req,res)=>{if(!['admin','therapist'].includes(req.user.role))return res.status(403).json({error:'forbidden'});db.prepare('UPDATE phoneme_samples SET label=?, reviewed_by=?, reviewed_at=? WHERE id=?').run(req.body.label,req.user.id,new Date().toISOString(),req.params.id);res.json({ok:true})});
app.listen(process.env.PORT||3000,()=>console.log('Fono+ backend running'));